#!/usr/bin/python

from subprocess import Popen, PIPE
import xml.dom.minidom
try:
    nvidiaSMI = xml.dom.minidom.parseString(Popen(["nvidia-smi", "-q", "-x"], stdout=PIPE).communicate()[0])
except:
    exit

print "<<<nvidia_gpu>>>"
i = 0
for gpu in nvidiaSMI.getElementsByTagName("gpu"):
    print("%d\tGPU_util\t%d" % (i, int(gpu.getElementsByTagName("utilization")[0].getElementsByTagName("gpu_util")[0].childNodes[0].data.split()[0])))
    print("%d\tmemory_used\t%d" % (i, int(gpu.getElementsByTagName("fb_memory_usage")[0].getElementsByTagName("used")[0].childNodes[0].data.split()[0])))
    print("%d\tmemory_total\t%d" % (i, int(gpu.getElementsByTagName("fb_memory_usage")[0].getElementsByTagName("total")[0].childNodes[0].data.split()[0])))
    print("%d\tmemory_util\t%d" % (i, (100*int(gpu.getElementsByTagName("fb_memory_usage")[0].getElementsByTagName("used")[0].childNodes[0].data.split()[0])/
        int(gpu.getElementsByTagName("fb_memory_usage")[0].getElementsByTagName("total")[0].childNodes[0].data.split()[0]))))

    try:
        print("%d\ttemperature\t%d" % (i, int(gpu.getElementsByTagName("temperature")[0].getElementsByTagName("gpu_temp")[0].childNodes[0].data.split()[0])))
    except ValueError:
        print("%d\ttemperature\t0" % (i))
    print("%d\tgraphics_clock\t%d" % (i, int(gpu.getElementsByTagName("clocks")[0].getElementsByTagName("graphics_clock")[0].childNodes[0].data.split()[0])))
    print("%d\tsm_clock\t%d" % (i, int(gpu.getElementsByTagName("clocks")[0].getElementsByTagName("sm_clock")[0].childNodes[0].data.split()[0])))
    print("%d\tmem_clock\t%d" % (i, int(gpu.getElementsByTagName("clocks")[0].getElementsByTagName("mem_clock")[0].childNodes[0].data.split()[0])))
    i += 1

